### ISSUE TITLE
Spell Save DC is always 'null' (0), even when cast using a player actor as the source

### ISSUE THREAD

**Issue by nirurin** [shemetz/roll-from-compendium#16]
Whether I cast a saving-throw spell as the 'roll from chat' actor (which should be DC10 by default) or from a player token (which is currently DC13), the actual saving throw is DC 'null', so it's basically impossible to fail the save haha. 

I wrote this as a separate issue to my other one, as I thought it would be easier to track :)

**Comment by shemetz** [comment]
Seems to be fixed in v1.5.0 (which is for Foundry v10)

**Comment by nirurin** [comment]
Ok cool, I was using Flat-DC when I was testing which worked, it was just the automatic DC that didn't. As you know I'm currently using a macro instead, but happy to help get this module working too as I think it's a cool concept (and the macro is certainly not as easy for people like me to deal with haha luckily someone made it for me!)
