### ISSUE TITLE
Defaults all character sheets to not using resources

### ISSUE THREAD

**Issue by shecrio** [shemetz/roll-from-compendium#18]
While the module is activated any pop ups after using an item, feature, or spell that has an associated charges, resource, spell slot, or template, all of the listed check boxes default to unchecked.
Noticed this just before a game so I will look for more details like in the console in a couple hours.

**Comment by shecrio** [comment]
It does, is it intended to apply to every actor or just (Quick Roll To Chat), because my experience is it applies to every actor in the world.

**Comment by shemetz** [comment]
All of them, but I can change it if you'd like.

The main issue though is that it's difficult to correctly match the usage resource of things that aren't spell slots.

**Comment by shecrio** [comment]
I think I just hadn't realized it was intended behavior, if there was a setting for toggling that on and off I would use it. If its easy to implement a setting to make it so GMs have it working as current, and Players have them checked by default that would be ideal. Either way feel free to mark this as closed if you'd like.

**Comment by lucky-trill** [comment]
I'm just going to echo that I would also love a setting to be able to change this behavior so using Quick Roll doesn't result in needing to check "consume resource" all the time.

**Comment by shemetz** [comment]
I'm going to fix/improve this in the next version: it will default to not consuming resources only for the special actor and for items that don't really belong to the actor, and yes consume for everything else (as normal in dnd5e)

**Comment by shemetz** [comment]
Fixed in v1.5.1
