### ISSUE TITLE
Can´t roll items in Simple World Building

### ISSUE THREAD

**Issue by Dedegugu0** [shemetz/roll-from-compendium#19]
Hey! I´m using Simple World Building to test some systems and I noticed that it impossible to roll items there, so I searched and found this module that would solve the problem, unfortunately it isn´t working as intendend, neither item is rolled, no matter what I do to it. I know the module is most used por PF2e and DND, but it fits perfectly in SWB and would help a lot of indie developers and people that just wants to play some smalls rpgs in foundry!

Hope I´m just being dumb and it works normally, but if don´t, I think it deserves a look up.

**Comment by shemetz** [comment]
Fixed in v1.5.2, thanks for the report!
