### ISSUE TITLE
[Bug] Can't send to chat

### ISSUE THREAD

**Issue by ChasarooniZ** [shemetz/roll-from-compendium#28]
![image](https://github.com/shemetz/roll-from-compendium/assets/79132112/3b0c6b5e-6abf-4298-8bef-538a7250da5e)
![image](https://github.com/shemetz/roll-from-compendium/assets/79132112/6ee48acf-5fd6-4470-b0ab-6b855ce80041)

(this is me trying to send an item to chat as GM)

**Comment by shemetz** [comment]
I can't reproduce this bug.

1. Was that in module version 1.7.3?
2. Does this happen to you with any existing item?  ("Broken clock" looks like a homebrew thing)
3. Was the item in a compendium or in the items directory, or something else?
4. Were there any other error messages before this?

**Comment by ChasarooniZ** [comment]
Hi, I believe I didn't have Setting  you mentioned in #2 enabled. Works perfectly fine now, thank you for your support. Really appreciate the modu,e
